/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompareQwicBikeResponseResult model module.
 * @module model/CompareQwicBikeResponseResult
 * @version 0.0.1
 */
class CompareQwicBikeResponseResult {
    /**
     * Constructs a new <code>CompareQwicBikeResponseResult</code>.
     * @alias module:model/CompareQwicBikeResponseResult
     */
    constructor() { 
        
        CompareQwicBikeResponseResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompareQwicBikeResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompareQwicBikeResponseResult} obj Optional instance to populate.
     * @return {module:model/CompareQwicBikeResponseResult} The populated <code>CompareQwicBikeResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompareQwicBikeResponseResult();

            if (data.hasOwnProperty('compare_type')) {
                obj['compare_type'] = ApiClient.convertToType(data['compare_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} compare_type
 */
CompareQwicBikeResponseResult.prototype['compare_type'] = undefined;






export default CompareQwicBikeResponseResult;

