/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PartMeta from './PartMeta';

/**
 * The CompareBikeRequest model module.
 * @module model/CompareBikeRequest
 * @version 0.0.1
 */
class CompareBikeRequest {
    /**
     * Constructs a new <code>CompareBikeRequest</code>.
     * @alias module:model/CompareBikeRequest
     * @param vin {String} 
     * @param parts {Array.<module:model/PartMeta>} 
     */
    constructor(vin, parts) { 
        
        CompareBikeRequest.initialize(this, vin, parts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, vin, parts) { 
        obj['vin'] = vin;
        obj['parts'] = parts;
    }

    /**
     * Constructs a <code>CompareBikeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompareBikeRequest} obj Optional instance to populate.
     * @return {module:model/CompareBikeRequest} The populated <code>CompareBikeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompareBikeRequest();

            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
            if (data.hasOwnProperty('parts')) {
                obj['parts'] = ApiClient.convertToType(data['parts'], [PartMeta]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} vin
 */
CompareBikeRequest.prototype['vin'] = undefined;

/**
 * @member {Array.<module:model/PartMeta>} parts
 */
CompareBikeRequest.prototype['parts'] = undefined;






export default CompareBikeRequest;

