/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CompareQwicBikeResponseResult from './CompareQwicBikeResponseResult';

/**
 * The CompareQwicBikeResponse model module.
 * @module model/CompareQwicBikeResponse
 * @version 0.0.1
 */
class CompareQwicBikeResponse {
    /**
     * Constructs a new <code>CompareQwicBikeResponse</code>.
     * @alias module:model/CompareQwicBikeResponse
     */
    constructor() { 
        
        CompareQwicBikeResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompareQwicBikeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompareQwicBikeResponse} obj Optional instance to populate.
     * @return {module:model/CompareQwicBikeResponse} The populated <code>CompareQwicBikeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompareQwicBikeResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = CompareQwicBikeResponseResult.constructFromObject(data['result']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CompareQwicBikeResponseResult} result
 */
CompareQwicBikeResponse.prototype['result'] = undefined;






export default CompareQwicBikeResponse;

