/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PartMeta from './PartMeta';

/**
 * The CreateBikeRequest model module.
 * @module model/CreateBikeRequest
 * @version 0.0.1
 */
class CreateBikeRequest {
    /**
     * Constructs a new <code>CreateBikeRequest</code>.
     * @alias module:model/CreateBikeRequest
     * @param vin {String} 
     * @param specId {Number} 
     * @param parts {Array.<module:model/PartMeta>} 
     */
    constructor(vin, specId, parts) { 
        
        CreateBikeRequest.initialize(this, vin, specId, parts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, vin, specId, parts) { 
        obj['vin'] = vin;
        obj['spec_id'] = specId;
        obj['parts'] = parts;
    }

    /**
     * Constructs a <code>CreateBikeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBikeRequest} obj Optional instance to populate.
     * @return {module:model/CreateBikeRequest} The populated <code>CreateBikeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBikeRequest();

            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
            if (data.hasOwnProperty('spec_id')) {
                obj['spec_id'] = ApiClient.convertToType(data['spec_id'], 'Number');
            }
            if (data.hasOwnProperty('parts')) {
                obj['parts'] = ApiClient.convertToType(data['parts'], [PartMeta]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} vin
 */
CreateBikeRequest.prototype['vin'] = undefined;

/**
 * @member {Number} spec_id
 */
CreateBikeRequest.prototype['spec_id'] = undefined;

/**
 * @member {Array.<module:model/PartMeta>} parts
 */
CreateBikeRequest.prototype['parts'] = undefined;






export default CreateBikeRequest;

