/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateBike model module.
 * @module model/CreateBike
 * @version 0.0.1
 */
class CreateBike {
    /**
     * Constructs a new <code>CreateBike</code>.
     * @alias module:model/CreateBike
     */
    constructor() { 
        
        CreateBike.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateBike</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBike} obj Optional instance to populate.
     * @return {module:model/CreateBike} The populated <code>CreateBike</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBike();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('spec_id')) {
                obj['spec_id'] = ApiClient.convertToType(data['spec_id'], 'Number');
            }
            if (data.hasOwnProperty('vin')) {
                obj['vin'] = ApiClient.convertToType(data['vin'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], {'String': 'String'});
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('invalided_at')) {
                obj['invalided_at'] = ApiClient.convertToType(data['invalided_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CreateBike.prototype['id'] = undefined;

/**
 * @member {Number} spec_id
 */
CreateBike.prototype['spec_id'] = undefined;

/**
 * @member {String} vin
 */
CreateBike.prototype['vin'] = undefined;

/**
 * @member {Object.<String, String>} meta
 */
CreateBike.prototype['meta'] = undefined;

/**
 * @member {String} created_at
 */
CreateBike.prototype['created_at'] = undefined;

/**
 * @member {String} invalided_at
 */
CreateBike.prototype['invalided_at'] = undefined;

/**
 * @member {String} updated_at
 */
CreateBike.prototype['updated_at'] = undefined;






export default CreateBike;

