/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Customer from './Customer';

/**
 * The CustomerResponse model module.
 * @module model/CustomerResponse
 * @version 0.0.1
 */
class CustomerResponse {
    /**
     * Constructs a new <code>CustomerResponse</code>.
     * @alias module:model/CustomerResponse
     */
    constructor() { 
        
        CustomerResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerResponse} obj Optional instance to populate.
     * @return {module:model/CustomerResponse} The populated <code>CustomerResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = Customer.constructFromObject(data['result']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Customer} result
 */
CustomerResponse.prototype['result'] = undefined;






export default CustomerResponse;

