/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.Firmware = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Firmware model module.
   * @module model/Firmware
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Firmware</code>.
   * @alias module:model/Firmware
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Firmware</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Firmware} obj Optional instance to populate.
   * @return {module:model/Firmware} The populated <code>Firmware</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('part_num')) {
        obj['part_num'] = ApiClient.convertToType(data['part_num'], 'String');
      }
      if (data.hasOwnProperty('hw_ver')) {
        obj['hw_ver'] = ApiClient.convertToType(data['hw_ver'], 'String');
      }
      if (data.hasOwnProperty('fw_kernel_ver')) {
        obj['fw_kernel_ver'] = ApiClient.convertToType(data['fw_kernel_ver'], 'String');
      }
      if (data.hasOwnProperty('fw_ver')) {
        obj['fw_ver'] = ApiClient.convertToType(data['fw_ver'], 'String');
      }
      if (data.hasOwnProperty('release_note')) {
        obj['release_note'] = ApiClient.convertToType(data['release_note'], 'String');
      }
      if (data.hasOwnProperty('files')) {
        obj['files'] = ApiClient.convertToType(data['files'], [{'String': 'String'}]);
      }
      if (data.hasOwnProperty('releases')) {
        obj['releases'] = ApiClient.convertToType(data['releases'], [{'String': 'String'}]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} part_num
   */
  exports.prototype['part_num'] = undefined;
  /**
   * @member {String} hw_ver
   */
  exports.prototype['hw_ver'] = undefined;
  /**
   * @member {String} fw_kernel_ver
   */
  exports.prototype['fw_kernel_ver'] = undefined;
  /**
   * @member {String} fw_ver
   */
  exports.prototype['fw_ver'] = undefined;
  /**
   * @member {String} release_note
   */
  exports.prototype['release_note'] = undefined;
  /**
   * @member {Array.<Object.<String, String>>} files
   */
  exports.prototype['files'] = undefined;
  /**
   * @member {Array.<Object.<String, String>>} releases
   */
  exports.prototype['releases'] = undefined;



  return exports;
}));


