/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessageGatewayResponseResult model module.
 * @module model/MessageGatewayResponseResult
 * @version 0.0.1
 */
class MessageGatewayResponseResult {
    /**
     * Constructs a new <code>MessageGatewayResponseResult</code>.
     * @alias module:model/MessageGatewayResponseResult
     */
    constructor() { 
        
        MessageGatewayResponseResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessageGatewayResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageGatewayResponseResult} obj Optional instance to populate.
     * @return {module:model/MessageGatewayResponseResult} The populated <code>MessageGatewayResponseResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageGatewayResponseResult();

            if (data.hasOwnProperty('NewVersion')) {
                obj['NewVersion'] = ApiClient.convertToType(data['NewVersion'], 'String');
            }
            if (data.hasOwnProperty('DownloadUrl')) {
                obj['DownloadUrl'] = ApiClient.convertToType(data['DownloadUrl'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} NewVersion
 */
MessageGatewayResponseResult.prototype['NewVersion'] = undefined;

/**
 * @member {String} DownloadUrl
 */
MessageGatewayResponseResult.prototype['DownloadUrl'] = undefined;






export default MessageGatewayResponseResult;

