/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.MessageGatewayResponseResult = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The MessageGatewayResponseResult model module.
   * @module model/MessageGatewayResponseResult
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>MessageGatewayResponseResult</code>.
   * @alias module:model/MessageGatewayResponseResult
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>MessageGatewayResponseResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageGatewayResponseResult} obj Optional instance to populate.
   * @return {module:model/MessageGatewayResponseResult} The populated <code>MessageGatewayResponseResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('NewVersion')) {
        obj['NewVersion'] = ApiClient.convertToType(data['NewVersion'], 'String');
      }
      if (data.hasOwnProperty('DownloadUrl')) {
        obj['DownloadUrl'] = ApiClient.convertToType(data['DownloadUrl'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} NewVersion
   */
  exports.prototype['NewVersion'] = undefined;
  /**
   * @member {String} DownloadUrl
   */
  exports.prototype['DownloadUrl'] = undefined;



  return exports;
}));


