/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PartRequest model module.
 * @module model/PartRequest
 * @version 0.0.1
 */
class PartRequest {
    /**
     * Constructs a new <code>PartRequest</code>.
     * @alias module:model/PartRequest
     * @param partNum {String} 
     * @param barcode {String} 
     * @param fwVer {String} 
     */
    constructor(partNum, barcode, fwVer) { 
        
        PartRequest.initialize(this, partNum, barcode, fwVer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, partNum, barcode, fwVer) { 
        obj['part_num'] = partNum;
        obj['barcode'] = barcode;
        obj['fw_ver'] = fwVer;
    }

    /**
     * Constructs a <code>PartRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PartRequest} obj Optional instance to populate.
     * @return {module:model/PartRequest} The populated <code>PartRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartRequest();

            if (data.hasOwnProperty('part_num')) {
                obj['part_num'] = ApiClient.convertToType(data['part_num'], 'String');
            }
            if (data.hasOwnProperty('barcode')) {
                obj['barcode'] = ApiClient.convertToType(data['barcode'], 'String');
            }
            if (data.hasOwnProperty('fw_ver')) {
                obj['fw_ver'] = ApiClient.convertToType(data['fw_ver'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} part_num
 */
PartRequest.prototype['part_num'] = undefined;

/**
 * @member {String} barcode
 */
PartRequest.prototype['barcode'] = undefined;

/**
 * @member {String} fw_ver
 */
PartRequest.prototype['fw_ver'] = undefined;






export default PartRequest;

