/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.PartRequest = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The PartRequest model module.
   * @module model/PartRequest
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>PartRequest</code>.
   * @alias module:model/PartRequest
   * @class
   * @param partNum {String} 
   * @param barcode {String} 
   * @param fwVer {String} 
   */
  var exports = function(partNum, barcode, fwVer) {
    var _this = this;

    _this['part_num'] = partNum;
    _this['barcode'] = barcode;
    _this['fw_ver'] = fwVer;
  };

  /**
   * Constructs a <code>PartRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartRequest} obj Optional instance to populate.
   * @return {module:model/PartRequest} The populated <code>PartRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('part_num')) {
        obj['part_num'] = ApiClient.convertToType(data['part_num'], 'String');
      }
      if (data.hasOwnProperty('barcode')) {
        obj['barcode'] = ApiClient.convertToType(data['barcode'], 'String');
      }
      if (data.hasOwnProperty('fw_ver')) {
        obj['fw_ver'] = ApiClient.convertToType(data['fw_ver'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} part_num
   */
  exports.prototype['part_num'] = undefined;
  /**
   * @member {String} barcode
   */
  exports.prototype['barcode'] = undefined;
  /**
   * @member {String} fw_ver
   */
  exports.prototype['fw_ver'] = undefined;



  return exports;
}));


