/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Part model module.
 * @module model/Part
 * @version 0.0.1
 */
class Part {
    /**
     * Constructs a new <code>Part</code>.
     * @alias module:model/Part
     */
    constructor() { 
        
        Part.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Part</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Part} obj Optional instance to populate.
     * @return {module:model/Part} The populated <code>Part</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Part();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('part_num')) {
                obj['part_num'] = ApiClient.convertToType(data['part_num'], 'String');
            }
            if (data.hasOwnProperty('fw_ver')) {
                obj['fw_ver'] = ApiClient.convertToType(data['fw_ver'], 'String');
            }
            if (data.hasOwnProperty('barcode')) {
                obj['barcode'] = ApiClient.convertToType(data['barcode'], 'String');
            }
            if (data.hasOwnProperty('activated_at')) {
                obj['activated_at'] = ApiClient.convertToType(data['activated_at'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Part.prototype['id'] = undefined;

/**
 * @member {String} part_num
 */
Part.prototype['part_num'] = undefined;

/**
 * @member {String} fw_ver
 */
Part.prototype['fw_ver'] = undefined;

/**
 * @member {String} barcode
 */
Part.prototype['barcode'] = undefined;

/**
 * @member {String} activated_at
 */
Part.prototype['activated_at'] = undefined;

/**
 * @member {String} created_at
 */
Part.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
Part.prototype['updated_at'] = undefined;






export default Part;

