/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PartMeta model module.
 * @module model/PartMeta
 * @version 0.0.1
 */
class PartMeta {
    /**
     * Constructs a new <code>PartMeta</code>.
     * @alias module:model/PartMeta
     */
    constructor() { 
        
        PartMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PartMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PartMeta} obj Optional instance to populate.
     * @return {module:model/PartMeta} The populated <code>PartMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartMeta();

            if (data.hasOwnProperty('mid')) {
                obj['mid'] = ApiClient.convertToType(data['mid'], 'String');
            }
            if (data.hasOwnProperty('part_num')) {
                obj['part_num'] = ApiClient.convertToType(data['part_num'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} mid
 */
PartMeta.prototype['mid'] = undefined;

/**
 * @member {String} part_num
 */
PartMeta.prototype['part_num'] = undefined;






export default PartMeta;

