/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PartSpec from './PartSpec';

/**
 * The PartSpecResponse model module.
 * @module model/PartSpecResponse
 * @version 0.0.1
 */
class PartSpecResponse {
    /**
     * Constructs a new <code>PartSpecResponse</code>.
     * @alias module:model/PartSpecResponse
     */
    constructor() { 
        
        PartSpecResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PartSpecResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PartSpecResponse} obj Optional instance to populate.
     * @return {module:model/PartSpecResponse} The populated <code>PartSpecResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartSpecResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = PartSpec.constructFromObject(data['result']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/PartSpec} result
 */
PartSpecResponse.prototype['result'] = undefined;






export default PartSpecResponse;

