/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.Part = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The Part model module.
   * @module model/Part
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Part</code>.
   * @alias module:model/Part
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>Part</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Part} obj Optional instance to populate.
   * @return {module:model/Part} The populated <code>Part</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('part_num')) {
        obj['part_num'] = ApiClient.convertToType(data['part_num'], 'String');
      }
      if (data.hasOwnProperty('fw_ver')) {
        obj['fw_ver'] = ApiClient.convertToType(data['fw_ver'], 'String');
      }
      if (data.hasOwnProperty('barcode')) {
        obj['barcode'] = ApiClient.convertToType(data['barcode'], 'String');
      }
      if (data.hasOwnProperty('activated_at')) {
        obj['activated_at'] = ApiClient.convertToType(data['activated_at'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} part_num
   */
  exports.prototype['part_num'] = undefined;
  /**
   * @member {String} fw_ver
   */
  exports.prototype['fw_ver'] = undefined;
  /**
   * @member {String} barcode
   */
  exports.prototype['barcode'] = undefined;
  /**
   * @member {String} activated_at
   */
  exports.prototype['activated_at'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


