/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Firmware from './Firmware';

/**
 * The QueryFirmwareResponse model module.
 * @module model/QueryFirmwareResponse
 * @version 0.0.1
 */
class QueryFirmwareResponse {
    /**
     * Constructs a new <code>QueryFirmwareResponse</code>.
     * @alias module:model/QueryFirmwareResponse
     */
    constructor() { 
        
        QueryFirmwareResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueryFirmwareResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QueryFirmwareResponse} obj Optional instance to populate.
     * @return {module:model/QueryFirmwareResponse} The populated <code>QueryFirmwareResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryFirmwareResponse();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], [Firmware]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Firmware>} result
 */
QueryFirmwareResponse.prototype['result'] = undefined;






export default QueryFirmwareResponse;

