/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.QwicBikeModel = factory(root.Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The QwicBikeModel model module.
   * @module model/QwicBikeModel
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>QwicBikeModel</code>.
   * @alias module:model/QwicBikeModel
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>QwicBikeModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QwicBikeModel} obj Optional instance to populate.
   * @return {module:model/QwicBikeModel} The populated <code>QwicBikeModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('valid_frame_number')) {
        obj['valid_frame_number'] = ApiClient.convertToType(data['valid_frame_number'], 'String');
      }
      if (data.hasOwnProperty('qwic_bike_model')) {
        obj['qwic_bike_model'] = ApiClient.convertToType(data['qwic_bike_model'], 'String');
      }
      if (data.hasOwnProperty('product_code')) {
        obj['product_code'] = ApiClient.convertToType(data['product_code'], 'String');
      }
      if (data.hasOwnProperty('axa_enabled')) {
        obj['axa_enabled'] = ApiClient.convertToType(data['axa_enabled'], 'Boolean');
      }
      if (data.hasOwnProperty('app_compatible')) {
        obj['app_compatible'] = ApiClient.convertToType(data['app_compatible'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} valid_frame_number
   */
  exports.prototype['valid_frame_number'] = undefined;
  /**
   * @member {String} qwic_bike_model
   */
  exports.prototype['qwic_bike_model'] = undefined;
  /**
   * @member {String} product_code
   */
  exports.prototype['product_code'] = undefined;
  /**
   * @member {Boolean} axa_enabled
   */
  exports.prototype['axa_enabled'] = undefined;
  /**
   * @member {Boolean} app_compatible
   */
  exports.prototype['app_compatible'] = undefined;



  return exports;
}));


