/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QwicBikeModel model module.
 * @module model/QwicBikeModel
 * @version 0.0.1
 */
class QwicBikeModel {
    /**
     * Constructs a new <code>QwicBikeModel</code>.
     * @alias module:model/QwicBikeModel
     */
    constructor() { 
        
        QwicBikeModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QwicBikeModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QwicBikeModel} obj Optional instance to populate.
     * @return {module:model/QwicBikeModel} The populated <code>QwicBikeModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QwicBikeModel();

            if (data.hasOwnProperty('valid_frame_number')) {
                obj['valid_frame_number'] = ApiClient.convertToType(data['valid_frame_number'], 'String');
            }
            if (data.hasOwnProperty('qwic_bike_model')) {
                obj['qwic_bike_model'] = ApiClient.convertToType(data['qwic_bike_model'], 'String');
            }
            if (data.hasOwnProperty('product_code')) {
                obj['product_code'] = ApiClient.convertToType(data['product_code'], 'String');
            }
            if (data.hasOwnProperty('axa_enabled')) {
                obj['axa_enabled'] = ApiClient.convertToType(data['axa_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('app_compatible')) {
                obj['app_compatible'] = ApiClient.convertToType(data['app_compatible'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} valid_frame_number
 */
QwicBikeModel.prototype['valid_frame_number'] = undefined;

/**
 * @member {String} qwic_bike_model
 */
QwicBikeModel.prototype['qwic_bike_model'] = undefined;

/**
 * @member {String} product_code
 */
QwicBikeModel.prototype['product_code'] = undefined;

/**
 * @member {Boolean} axa_enabled
 */
QwicBikeModel.prototype['axa_enabled'] = undefined;

/**
 * @member {Boolean} app_compatible
 */
QwicBikeModel.prototype['app_compatible'] = undefined;






export default QwicBikeModel;

