/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateBikeRequest from '../model/CreateBikeRequest';
import CreateBikeResponse from '../model/CreateBikeResponse';

/**
* Bike service.
* @module api/BikeApi
* @version 0.0.1
*/
export default class BikeApi {

    /**
    * Constructs a new BikeApi. 
    * @alias module:api/BikeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createBike operation.
     * @callback module:api/BikeApi~createBikeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateBikeResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a bike
     * @param {String} version api version
     * @param {module:model/CreateBikeRequest} body create bike body parameters
     * @param {module:api/BikeApi~createBikeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateBikeResponse}
     */
    createBike(version, body, callback) {
      let postBody = body;
      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling createBike");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createBike");
      }

      let pathParams = {
        'version': version
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['*/*', 'application/json'];
      let returnType = CreateBikeResponse;
      return this.apiClient.callApi(
        '/{version}/bike', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
