/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MessageGatewayResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/MessageGatewayResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.Api) {
      root.Api = {};
    }
    root.Api.MessageGatewayApi = factory(root.Api.ApiClient, root.Api.MessageGatewayResponse);
  }
}(this, function(ApiClient, MessageGatewayResponse) {
  'use strict';

  /**
   * MessageGateway service.
   * @module api/MessageGatewayApi
   * @version 0.0.1
   */

  /**
   * Constructs a new MessageGatewayApi. 
   * @alias module:api/MessageGatewayApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getMessageGateway operation.
     * @callback module:api/MessageGatewayApi~getMessageGatewayCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessageGatewayResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get message gateway
     * @param {String} version api version
     * @param {module:api/MessageGatewayApi~getMessageGatewayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessageGatewayResponse}
     */
    this.getMessageGateway = function(version, callback) {
      var postBody = null;
      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling getMessageGateway");
      }

      var pathParams = {
        'version': version
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Authorization'];
      var contentTypes = [];
      var accepts = ['*/*', 'application/json'];
      var returnType = MessageGatewayResponse;
      return this.apiClient.callApi(
        '/{version}/message_gateway/version', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }
  };

  return exports;
}));
