/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MessageGatewayResponse from '../model/MessageGatewayResponse';

/**
* MessageGateway service.
* @module api/MessageGatewayApi
* @version 0.0.1
*/
export default class MessageGatewayApi {

    /**
    * Constructs a new MessageGatewayApi. 
    * @alias module:api/MessageGatewayApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getMessageGateway operation.
     * @callback module:api/MessageGatewayApi~getMessageGatewayCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessageGatewayResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get message gateway
     * @param {String} version api version
     * @param {module:api/MessageGatewayApi~getMessageGatewayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessageGatewayResponse}
     */
    getMessageGateway(version, callback) {
      let postBody = null;
      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling getMessageGateway");
      }

      let pathParams = {
        'version': version
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['*/*', 'application/json'];
      let returnType = MessageGatewayResponse;
      return this.apiClient.callApi(
        '/{version}/message_gateway/version', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
