/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PartSpecResponse from '../model/PartSpecResponse';

/**
* PartSpec service.
* @module api/PartSpecApi
* @version 0.0.1
*/
export default class PartSpecApi {

    /**
    * Constructs a new PartSpecApi. 
    * @alias module:api/PartSpecApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getPartSpec operation.
     * @callback module:api/PartSpecApi~getPartSpecCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PartSpecResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a part spec
     * @param {String} version api version
     * @param {String} specId spec id
     * @param {module:api/PartSpecApi~getPartSpecCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PartSpecResponse}
     */
    getPartSpec(version, specId, callback) {
      let postBody = null;
      // verify the required parameter 'version' is set
      if (version === undefined || version === null) {
        throw new Error("Missing the required parameter 'version' when calling getPartSpec");
      }
      // verify the required parameter 'specId' is set
      if (specId === undefined || specId === null) {
        throw new Error("Missing the required parameter 'specId' when calling getPartSpec");
      }

      let pathParams = {
        'version': version,
        'spec_id': specId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Authorization'];
      let contentTypes = [];
      let accepts = ['*/*', 'application/json'];
      let returnType = PartSpecResponse;
      return this.apiClient.callApi(
        '/{version}/part_spec/{spec_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
