/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.Firmware();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Firmware', function() {
    it('should create an instance of Firmware', function() {
      // uncomment below and update the code to test Firmware
      //var instane = new Api.Firmware();
      //expect(instance).to.be.a(Api.Firmware);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new Api.Firmware();
      //expect(instance).to.be();
    });

    it('should have the property partNum (base name: "part_num")', function() {
      // uncomment below and update the code to test the property partNum
      //var instane = new Api.Firmware();
      //expect(instance).to.be();
    });

    it('should have the property hwVer (base name: "hw_ver")', function() {
      // uncomment below and update the code to test the property hwVer
      //var instane = new Api.Firmware();
      //expect(instance).to.be();
    });

    it('should have the property fwKernelVer (base name: "fw_kernel_ver")', function() {
      // uncomment below and update the code to test the property fwKernelVer
      //var instane = new Api.Firmware();
      //expect(instance).to.be();
    });

    it('should have the property fwVer (base name: "fw_ver")', function() {
      // uncomment below and update the code to test the property fwVer
      //var instane = new Api.Firmware();
      //expect(instance).to.be();
    });

    it('should have the property releaseNote (base name: "release_note")', function() {
      // uncomment below and update the code to test the property releaseNote
      //var instane = new Api.Firmware();
      //expect(instance).to.be();
    });

    it('should have the property files (base name: "files")', function() {
      // uncomment below and update the code to test the property files
      //var instane = new Api.Firmware();
      //expect(instance).to.be();
    });

    it('should have the property releases (base name: "releases")', function() {
      // uncomment below and update the code to test the property releases
      //var instane = new Api.Firmware();
      //expect(instance).to.be();
    });

  });

}));
