/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.PartSpec();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PartSpec', function() {
    it('should create an instance of PartSpec', function() {
      // uncomment below and update the code to test PartSpec
      //var instance = new Api.PartSpec();
      //expect(instance).to.be.a(Api.PartSpec);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property projectCode (base name: "project_code")', function() {
      // uncomment below and update the code to test the property projectCode
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property supplierId (base name: "supplier_id")', function() {
      // uncomment below and update the code to test the property supplierId
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customer_id")', function() {
      // uncomment below and update the code to test the property customerId
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property fwVer (base name: "fw_ver")', function() {
      // uncomment below and update the code to test the property fwVer
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property hwVer (base name: "hw_ver")', function() {
      // uncomment below and update the code to test the property hwVer
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property meta (base name: "meta")', function() {
      // uncomment below and update the code to test the property meta
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new Api.PartSpec();
      //expect(instance).to.be();
    });

  });

}));
