/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.3.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Api);
  }
}(this, function(expect, Api) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Api.QwicBikeModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QwicBikeModel', function() {
    it('should create an instance of QwicBikeModel', function() {
      // uncomment below and update the code to test QwicBikeModel
      //var instance = new Api.QwicBikeModel();
      //expect(instance).to.be.a(Api.QwicBikeModel);
    });

    it('should have the property validFrameNumber (base name: "valid_frame_number")', function() {
      // uncomment below and update the code to test the property validFrameNumber
      //var instance = new Api.QwicBikeModel();
      //expect(instance).to.be();
    });

    it('should have the property qwicBikeModel (base name: "qwic_bike_model")', function() {
      // uncomment below and update the code to test the property qwicBikeModel
      //var instance = new Api.QwicBikeModel();
      //expect(instance).to.be();
    });

    it('should have the property productCode (base name: "product_code")', function() {
      // uncomment below and update the code to test the property productCode
      //var instance = new Api.QwicBikeModel();
      //expect(instance).to.be();
    });

    it('should have the property axaEnabled (base name: "axa_enabled")', function() {
      // uncomment below and update the code to test the property axaEnabled
      //var instance = new Api.QwicBikeModel();
      //expect(instance).to.be();
    });

    it('should have the property appCompatible (base name: "app_compatible")', function() {
      // uncomment below and update the code to test the property appCompatible
      //var instance = new Api.QwicBikeModel();
      //expect(instance).to.be();
    });

  });

}));
